# Generated by Django 4.2.29 on 2026-06-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_loginlog_role_useraccount_accesstoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qingmastudent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱'),
        ),
    ]
