# Generated by Django 4.2.29 on 2026-06-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_qingmastudent_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developmentapplication',
            name='application_status',
            field=models.CharField(choices=[('待审批', '待审批'), ('已通过', '已通过'), ('已拒绝', '已拒绝'), ('已完成', '已完成')], default='待审批', max_length=20, verbose_name='审批状态'),
        ),
    ]
