# Generated by Django 4.2.29 on 2026-06-16 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_developmentapplication_application_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=20, verbose_name='学号')),
                ('role', models.CharField(blank=True, max_length=50, verbose_name='角色')),
                ('required_permission', models.CharField(max_length=100, verbose_name='需要的权限')),
                ('method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('path', models.CharField(max_length=500, verbose_name='请求路径')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='尝试时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_logs', to='management.useraccount')),
            ],
            options={
                'verbose_name': '权限日志',
                'verbose_name_plural': '权限日志',
                'db_table': 'permission_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
