# Generated by Django 4.2.29 on 2026-06-16 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_permissionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_student_id', models.CharField(blank=True, max_length=20, verbose_name='操作人学号')),
                ('operator_name', models.CharField(blank=True, max_length=50, verbose_name='操作人姓名')),
                ('operation_type', models.CharField(choices=[('create_role', '创建角色'), ('edit_role', '编辑角色'), ('delete_role', '删除角色'), ('assign_role', '分配角色'), ('remove_role', '移除角色'), ('change_permissions', '修改权限'), ('create_user', '创建用户'), ('edit_user', '编辑用户'), ('delete_user', '删除用户')], max_length=50, verbose_name='操作类型')),
                ('target_type', models.CharField(blank=True, help_text='角色/用户', max_length=50, verbose_name='目标类型')),
                ('target_id', models.IntegerField(blank=True, null=True, verbose_name='目标ID')),
                ('target_name', models.CharField(blank=True, max_length=100, verbose_name='目标名称')),
                ('change_detail', models.TextField(blank=True, help_text='JSON格式的详细变更内容', verbose_name='变更详情')),
                ('before_value', models.TextField(blank=True, help_text='变更前的数据', verbose_name='变更前值')),
                ('after_value', models.TextField(blank=True, help_text='变更后的数据', verbose_name='变更后值')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_change_logs', to='management.useraccount', verbose_name='操作人')),
            ],
            options={
                'verbose_name': '权限变更日志',
                'verbose_name_plural': '权限变更日志',
                'db_table': 'permission_change_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
