# Generated by Django 4.2.29 on 2026-06-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_permissionchangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('education', '学历'), ('college', '学院'), ('department', '部门'), ('position', '职务'), ('ethnicity', '民族'), ('party_status', '党员状态'), ('league_status', '团员状态'), ('activity_type', '活动类型'), ('material_category', '物资分类'), ('custom', '自定义')], max_length=50, verbose_name='分类')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='编码')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '数据字典',
                'verbose_name_plural': '数据字典',
                'db_table': 'data_dictionaries',
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
    ]
