[providers]
python = { version = "3.11" }

[build]
setup = ["pip install -r requirements.txt"]
build = ["python manage.py collectstatic --noinput"]

[start]
cmd = "python manage.py migrate --noinput && gunicorn --bind 0.0.0.0:$PORT myproject.wsgi:application"